#include <nds.h>
#include "text.h"
#include "font.h"

static const char *const text_es[T_COUNT] = {
	[T_LOADING] = "Cargando el cat\303\241logo...\nEspera unos instantes.",
	[T_START_SHOPPING] = "Comenzar a comprar",
	[T_NEWEST] = "T\303\255tulos m\303\241s recientes",
	[T_SETTINGS] = "Configuraci\303\263n",
	[T_WELCOME] = "Te damos la bienvenida a la\nTienda Nintendo DS.",
	[T_N_TITLES] = "T\303\255tulos disponibles: %d",
	[T_CATEGORIES] = "Categor\303\255as",
	[T_ALL] = "Todos los t\303\255tulos",
	[T_FREE] = "Gratis",
	[T_DOWNLOAD] = "Descargar",
	[T_REDOWNLOAD] = "Volver a descargar",
	[T_CONFIRM_DL] = "\302\277Quieres descargar\neste t\303\255tulo?",
	[T_ALREADY] = "Ya tienes este t\303\255tulo.\n\302\277Quieres volver a descargarlo?",
	[T_DOWNLOADING] = "Descargando...",
	[T_DONT_TURN_OFF] = "No apagues la consola ni retires\nla tarjeta durante la descarga.",
	[T_DL_DONE] = "La descarga se ha completado.",
	[T_DL_SAVED] = "Se ha guardado en:",
	[T_DL_FAILED] = "No se ha podido completar\nla descarga.",
	[T_NO_SD] = "No se ha podido acceder a la\ntarjeta SD. Comprueba que el\ncartucho tiene un controlador\nDLDI y vuelve a intentarlo.",
	[T_NO_STORES] = "Todav\303\255a no tienes ninguna tienda.\nToca \302\253A\303\261adir tienda\302\273 y escribe\nla direcci\303\263n de un servidor.",
	[T_EXIT_CONFIRM] = "\302\277Quieres salir de la\nTienda Nintendo DS?",
	[T_MUSIC] = "M\303\272sica",
	[T_FREE_SPACE] = "Espacio libre",
	[T_SIZE] = "Tama\303\261o",
	[T_FILE] = "Archivo",
	[T_HELP_LIST] = ICON_A " Ver   " ICON_B " Atr\303\241s",
	[T_HELP_MENU] = ICON_A " Aceptar",
	[T_ON] = "Activada",
	[T_OFF] = "Desactivada",
	[T_NO_SPACE] = "No hay espacio suficiente\nen la tarjeta SD.",
	[T_DL_CANCELLED] = "Se ha cancelado la descarga.",
	[T_CANCEL] = "Cancelar",
	[T_HELP_TITLE] = "Informaci\303\263n del t\303\255tulo",
	[T_SETTINGS_SAVED] = "Se ha guardado la configuraci\303\263n.",
	[T_CODE_SD] = "209601",
	[T_CODE_COPY] = "209620",
	[T_DL_REMAINING] = "%d%%",
	[T_OTHER] = "Otros",
	[T_CHOOSE_STORE] = "Elige una tienda",
	[T_CHANGE_STORE] = "Tiendas",
	[T_SOURCES_HELP] = "Elige una tienda o a\303\261ade una nueva.\nPara cambiar una, selecci\303\263nala\ny toca Editar (o pulsa X).",
	[T_EMPTY_STORE] = "Esta tienda todav\303\255a\nno tiene t\303\255tulos.",
	[T_CODE_WIFI] = "209610",
	[T_CODE_SERVER] = "209630",
	[T_CODE_DATA] = "209640",
	[T_RESUME_DL] = "Continuar la descarga",
	[T_RESUMING] = "Reanudando la descarga...",
	[T_DL_CAN_RESUME] = "Lo descargado se ha guardado:\npodr\303\241s continuar m\303\241s tarde.",
	[T_ADD_STORE] = "A\303\261adir tienda",
	[T_EDIT] = "Editar",
	[T_EDIT_STORE] = "Editar tienda",
	[T_STORE_HELP] = "Escribe la direcci\303\263n del servidor,\npor ejemplo http://192.168.1.10:8080\n\nSolo se admite HTTP, y la consola\nnecesita una red abierta o WEP.",
	[T_STORE_NAME] = "Nombre",
	[T_STORE_URL] = "Direcci\303\263n (URL)",
	[T_URL_HELP] = "Por ejemplo: http://192.168.1.10:8080\n" ICON_B " borrar \302\267 START aceptar \302\267 L/R teclado",
	[T_NAME_HELP] = "El nombre con el que aparecer\303\241 en la lista.\n" ICON_B " borrar \302\267 START aceptar \302\267 L/R teclado",
	[T_SAVE] = "Guardar",
	[T_SHOP_NAME] = "Tienda Nintendo DS",
	[T_DOWNLOADS_TO] = "Las descargas se guardan en la\nmisma carpeta que la tienda:",
	[T_OFFLINE] = "Sin conexi\303\263n:",
	[T_N_STORES] = "T\303\255tulos de %d tiendas",
	[T_SOURCE] = "Tienda",
	[T_STORES] = "Tiendas",
	[T_MERGED] = "Todas juntas",
	[T_SEPARATE] = "Por separado",
	[T_SOURCES_HELP_MERGED] = "Los t\303\255tulos de todas las tiendas\nse muestran juntos.\nToca una tienda para editarla.",
	[T_RECONNECTING] = "Se ha cortado la conexi\303\263n. Reintentando...",
	[T_DELETE_STORE] = "Borrar esta tienda",
	[T_NO_HTTPS] = "La consola no puede conectarse\na direcciones HTTPS.\nUsa una direcci\303\263n http://",
	[T_BAD_URL] = "La direcci\303\263n no es v\303\241lida.\nEjemplo: http://192.168.1.10:8080",
	[T_SAVE_FAILED] = "No se ha podido guardar\nen la tarjeta SD.",
	[T_CONFIRM_DELETE] = "\302\277Quieres borrar esta tienda?",
	[T_TOO_MANY_STORES] = "No se pueden a\303\261adir\nm\303\241s tiendas.",
	[T_TORRENTS] = "Torrents (experimental)",
	[T_TOR_DOWNLOAD] = "Descargar desde torrent",
	[T_TOR_HELP] = "Escribe el enlace completo de un\narchivo .torrent (http://...). La consola\ndescarga el .torrent y despu\303\251s su\ncontenido directamente de otros usuarios.\n\nExperimental: solo trackers http:// y\nudp://, sin DHT ni enlaces magnet.",
	[T_TOR_URL] = "Enlace del .torrent",
	[T_TOR_URL_HELP] = "Ejemplo: http://192.168.1.10/juego.torrent\n" ICON_B " borrar \302\267 START aceptar \302\267 L/R teclado",
	[T_TOR_FETCHING] = "Descargando el archivo .torrent...",
	[T_TOR_FETCH_FAILED] = "No se ha podido descargar\nel archivo .torrent.",
	[T_TOR_BAD] = "El archivo .torrent no es v\303\241lido:",
	[T_TOR_FILES] = "Elige un archivo",
	[T_TOR_PREPARE] = "Preparando el archivo en la SD...",
	[T_TOR_TRACKER] = "Pidiendo usuarios al tracker...",
	[T_TOR_SEARCH] = "Buscando usuarios...",
	[T_TOR_PEERS] = "Usuarios: %d (de %d) \302\267 %s/s",
	[T_SCAN_QR] = "Escanear c\303\263digo QR",
	[T_QR_HELP] = "Apunta la c\303\241mara al c\303\263digo QR.\nPuede ser la direcci\303\263n de una tienda\n(o Nombre|direcci\303\263n) o un .torrent.",
	[T_QR_FAILED] = "No se ha podido usar la c\303\241mara.",
	[T_QR_UNKNOWN] = "El c\303\263digo QR no contiene\nuna direcci\303\263n http://",
};

static const char *const text_en[T_COUNT] = {
	[T_LOADING] = "Loading the catalog...\nPlease wait.",
	[T_START_SHOPPING] = "Start Shopping",
	[T_NEWEST] = "Newest Arrivals",
	[T_SETTINGS] = "Settings",
	[T_WELCOME] = "Welcome to the\nNintendo DS Shop.",
	[T_N_TITLES] = "Available titles: %d",
	[T_CATEGORIES] = "Categories",
	[T_ALL] = "All Titles",
	[T_FREE] = "Free",
	[T_DOWNLOAD] = "Download",
	[T_REDOWNLOAD] = "Download Again",
	[T_CONFIRM_DL] = "Do you want to download\nthis title?",
	[T_ALREADY] = "You already have this title.\nDownload it again?",
	[T_DOWNLOADING] = "Downloading...",
	[T_DONT_TURN_OFF] = "Do not turn off the power or\nremove the card while downloading.",
	[T_DL_DONE] = "Download complete.",
	[T_DL_SAVED] = "Saved to:",
	[T_DL_FAILED] = "The download could not\nbe completed.",
	[T_NO_SD] = "Unable to access the SD card.\nMake sure the flashcard has a\nDLDI driver and try again.",
	[T_NO_STORES] = "You have not added any shops yet.\nTouch \"Add Shop\" and enter the\naddress of a server.",
	[T_EXIT_CONFIRM] = "Do you want to quit the\nNintendo DS Shop?",
	[T_MUSIC] = "Music",
	[T_FREE_SPACE] = "Free space",
	[T_SIZE] = "Size",
	[T_FILE] = "File",
	[T_HELP_LIST] = ICON_A " View   " ICON_B " Back",
	[T_HELP_MENU] = ICON_A " OK",
	[T_ON] = "On",
	[T_OFF] = "Off",
	[T_NO_SPACE] = "There is not enough free\nspace on the SD card.",
	[T_DL_CANCELLED] = "The download was cancelled.",
	[T_CANCEL] = "Cancel",
	[T_HELP_TITLE] = "Title Information",
	[T_SETTINGS_SAVED] = "Settings saved.",
	[T_CODE_SD] = "209601",
	[T_CODE_COPY] = "209620",
	[T_DL_REMAINING] = "%d%%",
	[T_OTHER] = "Other",
	[T_CHOOSE_STORE] = "Choose a Shop",
	[T_CHANGE_STORE] = "Shops",
	[T_SOURCES_HELP] = "Choose a shop or add a new one.\nTo change one, select it and\ntouch Edit (or press X).",
	[T_EMPTY_STORE] = "This shop has no\ntitles yet.",
	[T_CODE_WIFI] = "209610",
	[T_CODE_SERVER] = "209630",
	[T_CODE_DATA] = "209640",
	[T_RESUME_DL] = "Resume Download",
	[T_RESUMING] = "Resuming download...",
	[T_DL_CAN_RESUME] = "The downloaded data was kept:\nyou can resume later.",
	[T_ADD_STORE] = "Add Shop",
	[T_EDIT] = "Edit",
	[T_EDIT_STORE] = "Edit Shop",
	[T_STORE_HELP] = "Enter the server address, for\nexample http://192.168.1.10:8080\n\nOnly HTTP is supported, and the\nsystem needs an open or WEP network.",
	[T_STORE_NAME] = "Name",
	[T_STORE_URL] = "Address (URL)",
	[T_URL_HELP] = "For example: http://192.168.1.10:8080\n" ICON_B " delete \302\267 START OK \302\267 L/R keyboard",
	[T_NAME_HELP] = "The name shown in the list.\n" ICON_B " delete \302\267 START OK \302\267 L/R keyboard",
	[T_SAVE] = "Save",
	[T_SHOP_NAME] = "Nintendo DS Shop",
	[T_DOWNLOADS_TO] = "Downloads are saved in the\nsame folder as the shop:",
	[T_OFFLINE] = "Offline:",
	[T_N_STORES] = "Titles from %d shops",
	[T_SOURCE] = "Shop",
	[T_STORES] = "Shops",
	[T_MERGED] = "All Together",
	[T_SEPARATE] = "Separately",
	[T_SOURCES_HELP_MERGED] = "Titles from all shops are\nshown together.\nTouch a shop to edit it.",
	[T_RECONNECTING] = "Connection lost. Retrying...",
	[T_DELETE_STORE] = "Delete This Shop",
	[T_NO_HTTPS] = "The system cannot connect\nto HTTPS addresses.\nUse an http:// address.",
	[T_BAD_URL] = "The address is not valid.\nExample: http://192.168.1.10:8080",
	[T_SAVE_FAILED] = "Could not save to\nthe SD card.",
	[T_CONFIRM_DELETE] = "Delete this shop?",
	[T_TOO_MANY_STORES] = "No more shops\ncan be added.",
	[T_TORRENTS] = "Torrents (experimental)",
	[T_TOR_DOWNLOAD] = "Download from Torrent",
	[T_TOR_HELP] = "Enter the full link to a .torrent\nfile (http://...). The system downloads\nthe .torrent and then its contents\ndirectly from other users.\n\nExperimental: only http:// and udp://\ntrackers, no DHT or magnet links.",
	[T_TOR_URL] = "Link to the .torrent",
	[T_TOR_URL_HELP] = "Example: http://192.168.1.10/game.torrent\n" ICON_B " delete \302\267 START OK \302\267 L/R keyboard",
	[T_TOR_FETCHING] = "Downloading the .torrent file...",
	[T_TOR_FETCH_FAILED] = "Could not download\nthe .torrent file.",
	[T_TOR_BAD] = "The .torrent file is not valid:",
	[T_TOR_FILES] = "Choose a File",
	[T_TOR_PREPARE] = "Preparing the file on the SD card...",
	[T_TOR_TRACKER] = "Asking the tracker for users...",
	[T_TOR_SEARCH] = "Looking for users...",
	[T_TOR_PEERS] = "Users: %d (of %d) \302\267 %s/s",
	[T_SCAN_QR] = "Scan QR Code",
	[T_QR_HELP] = "Point the camera at the QR code.\nIt can be a shop address\n(or Name|address) or a .torrent.",
	[T_QR_FAILED] = "The camera could not be used.",
	[T_QR_UNKNOWN] = "The QR code does not contain\nan http:// address.",
};

static int lang = 1;

void text_init(void) {
	int l = PersonalData->language;
	// No kana/kanji in the trimmed font: Japanese and Chinese use English
	lang = (l >= 1 && l <= 5) ? l : 1;
}

int text_lang(void) { return lang; }

const char *bmg(int id) {
	if (id < 0 || id >= BMG_COUNT) return "";
	const char *s = bmg_text[lang][id];
	return *s ? s : bmg_text[1][id];
}

const char *txt(TextId id) {
	const char *s = (lang == 5 ? text_es : text_en)[id];
	return s ? s : text_en[id];
}
