// Texts: the shop's originals (BMG) plus the homebrew's own.
#pragma once
#include "assets_gen.h"

// Indices within shop.bmg
enum {
	B_RETRY = 6, B_BLOCK = 7, B_BLOCKS = 8, B_ERROR_CODE = 17,
	B_ERR_NO_AP = 35, B_ERR_SERVER = 47, B_CONNECTING = 74,
	B_ERR_GENERIC = 49, B_ERR_SEE_TOP = 69, B_MAIN_MENU = 79, B_DSI_MENU = 80,
	B_BACK = 82, B_NO = 83, B_OK = 84, B_POINT = 86, B_POINTS = 87,
	B_RESTART = 88, B_SHOP_TITLE = 90, B_QUIT = 93, B_YES = 95,
};

typedef enum {
	T_LOADING, T_START_SHOPPING, T_NEWEST, T_SETTINGS, T_WELCOME, T_N_TITLES,
	T_CATEGORIES, T_ALL, T_FREE, T_DOWNLOAD, T_REDOWNLOAD, T_CONFIRM_DL,
	T_ALREADY, T_DOWNLOADING, T_DONT_TURN_OFF, T_DL_DONE, T_DL_SAVED,
	T_DL_FAILED, T_NO_SD, T_NO_STORES, T_EXIT_CONFIRM, T_MUSIC,
	T_FREE_SPACE, T_SIZE, T_FILE, T_HELP_LIST, T_HELP_MENU, T_ON, T_OFF,
	T_NO_SPACE, T_DL_CANCELLED, T_CANCEL, T_HELP_TITLE,
	T_SETTINGS_SAVED, T_CODE_SD, T_CODE_COPY, T_DL_REMAINING, T_OTHER,
	T_CHOOSE_STORE, T_CHANGE_STORE, T_SOURCES_HELP, T_EMPTY_STORE,
	T_CODE_WIFI, T_CODE_SERVER, T_CODE_DATA,
	T_RESUME_DL, T_RESUMING, T_DL_CAN_RESUME, T_ADD_STORE, T_EDIT, T_EDIT_STORE,
	T_STORE_HELP, T_STORE_NAME, T_STORE_URL, T_URL_HELP, T_NAME_HELP, T_SAVE,
	T_OFFLINE, T_N_STORES, T_SOURCE, T_STORES, T_MERGED, T_SEPARATE, T_SOURCES_HELP_MERGED,
	T_SHOP_NAME, T_DOWNLOADS_TO, T_DELETE_STORE, T_RECONNECTING, T_NO_HTTPS, T_BAD_URL, T_SAVE_FAILED, T_CONFIRM_DELETE, T_TOO_MANY_STORES,
	T_TORRENTS, T_TOR_DOWNLOAD, T_TOR_HELP, T_TOR_URL, T_TOR_URL_HELP, T_TOR_FETCHING, T_TOR_FETCH_FAILED,
	T_TOR_BAD, T_TOR_FILES, T_TOR_PREPARE, T_TOR_TRACKER, T_TOR_SEARCH, T_TOR_PEERS, T_SCAN_QR,
	T_QR_HELP, T_QR_FAILED, T_QR_UNKNOWN,
	T_COUNT
} TextId;

void text_init(void);
const char *bmg(int id);
const char *txt(TextId id);
int text_lang(void);	// 0 jp, 1 en, 2 fr, 3 de, 4 it, 5 es (firmware language)
