"""Generates homebrew/arm7/source/snd_tables.h (SSEQ sequencer tables)."""
import math
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
out = ['// Generated by tools/gen_snd_tables.py', '#pragma once', '#include <nds/ndstypes.h>', '']

pitch = [round(65536 * (2 ** (i / 768) - 1)) for i in range(768)]
out.append('static const u16 pitch_tbl[768] = {' + ','.join(map(str, pitch)) + '};')

# Volume for every 0.1 dB from -72.3 to 0; the channel divider is chosen separately.
vol = []
for i in range(724):
    db = i - 723
    a = 10 ** (db / 200)
    f = 16 if db < -240 else 4 if db < -120 else 2 if db < -60 else 1
    vol.append(min(127, round(127 * a * f)))
out.append('static const u8 vol_tbl[724] = {' + ','.join(map(str, vol)) + '};')

dbsq = [-32768] + [max(-723, round(400 * math.log10(x / 127))) for x in range(1, 128)]
out.append('static const s16 dbsq_tbl[128] = {' + ','.join(map(str, dbsq)) + '};')

sine = [round(127 * math.sin(math.pi / 2 * i / 32)) for i in range(33)]
out.append('static const s8 sine_tbl[33] = {' + ','.join(map(str, sine)) + '};')

attack = [0x00, 0x01, 0x05, 0x0E, 0x1A, 0x26, 0x33, 0x3F, 0x49, 0x54, 0x5C, 0x64, 0x6D, 0x74, 0x7B, 0x7F, 0x84, 0x89, 0x8F]
out.append('static const u8 attack_tbl[19] = {' + ','.join(map(str, attack)) + '};')

with open(os.path.join(ROOT, 'homebrew', 'arm7', 'source', 'snd_tables.h'), 'w', newline='\n') as f:
    f.write('\n'.join(out) + '\n')
